name = "Baguetus Place"
author = "Baguette Deluxe"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d51ab8e4d27e9826bc33dcfd3c162e613729c7c724db444d64d179becd1cb46"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
